
## Close Project

### Final checks on Genomic Status before closing

On [GenStat](https://genomics-status.scilifelab.se/project/<project_id>), go to the _Links_ tab:

 - [ ] Check that the _Project Folder_ link is working

In the _Project information_ tab, and check the following:

- [ ] The _Lanes Ordered_ matches the _Lanes started_
- [ ] The number of samples is correct in both _Samples_ and _Charon Status_ tables

- [ ] There are no running notes that require the project to be kept open

In the _User communication_ tab:

- [ ] Check that there is no ongoing ticket

If there is any open ticket, contact the project coordinator.

Click on the [bioinfo tab](<genstat_url>/bioinfo/<project_id>) and check the following:

- [ ] The QC boxes are correctly set
- [ ] The delivery dates are set

On LIMS, click on the magnifying glass icon, select _Project_ from the dropdown menu and search for the project id (<project_id>). In the list that appears:

- [ ] Check that all samples have ONLY the _Project Summary_ button

### Final step on Google Drive

On [GenStat](https://genomics-status.scilifelab.se/project/<project_id>), go to the _Links_ tab, and open the _Project Folder_ link.

- [ ] Go to *_Quality Assurance system* > Projects > Ongoing projects > `<username>_<year>_<index>`
- [ ] Move the project folder to the folder *_Can be Archived*

### Final steps in LIMS

On the LIMS _Project summary_ page, check the following:

- [ ] All samples sequence field is signed
- [ ] If required, Best Practice analysis field is signed
- [ ] All raw data delivered field is signed
- [ ] All samples show the correct number of reads
  - If not, click on _Reads aggregation | Run_ and then _Record changes | Run_
- [ ] _QC_ field has the correct status
- [ ] _Status (manual)/Set Status (manual)_ field is set to either _Finished_ or _Aborted_
  - If not, set it to _Finished_, but leave the _Aborted_ as is, if any
- [ ] The _Set App QC_ field is set to _N/A_, if no best practice analysis was performed

- [ ] Upload the project summary report

Once all the checks are done:

- [ ] Click on _Record changes | Run_
- [ ] Click on _Next Steps_

- [ ] Apply the _Mark protocol as complete_ for all samples
- [ ] Click on _Finish Step_

### Closing the project on LIMS

Go to the _Project and Samples_ tab and search for the project name.

- [ ] Set the project status to _Closed_
- [ ] Click on _Save_

On GenStat:

- [ ] Write a running note that the project has been closed on LIMS

```text
Project closed in LIMS.
```