
## Data delivery

### Generating reports

- [ ] Log into Miarka
- [ ] Move to the project directory and submit the report job:
```bash
cd <ngi_path>/ANALYSIS/<project_id> && ngi_reports project_summary -p <project_id> -s '<author_name>'
```

This step creates the `reports` directory.

Open the markdown file in the `reports` directory, and check the following:

- [ ] The accreditation specifications are correct
- [ ] The read counts are correct
- [ ] The index sequences are correct
- [ ] All flowcells are listed
- [ ] No deviation note or notification of manual steps should be added
- [ ] No new samples should be added

If any of the above points are incorrect, you can edit the markdown file directly, and then run the following command to re-generate the final report:
```bash
make_report <project_name>_project_summary.md
```

- [ ] Transfer the multiqc report and the `reports` directory to the local machine for later use. From your local machine, you can run a command similar to this:

```bash
mkdir <local_reports_path>/<project_name>
cd <local_reports_path>/<project_name>
rsync -avP --exclude="*_multiqc_report_data" --exclude="qc_ngi" miarka1:<ngi_path>/ANALYSIS/<project_id>/ .
```

### Standard DDS delivery

- [ ] Check in [Charon](<charon_url>/project/<project_id>) that the _Status_ column is _STALE_ for all samples to be delivered

- [ ] Open a `screen` session
```bash
screen -S <user_signature>_<project_id>
```

- [ ] Run TACA to start the soft-stage delivery:
```bash
taca -c <config_path>/TACA/sthlm_taca_<instrument_config>_delivery.yml deliver --ignore-analysis-status --stage_only project <project_id>
```

::: {.callout-note}
Remember to change the above command if the project was processed with Sarek (`wgs`) or NGI-RNAseq (`rna`).
:::

- [ ] Check in [Charon](<charon_url>/project/<project_id>) that the _Delivery status_ column is _STAGED_ for all samples

- [ ] Log into DDS
```bash
dds auth login
```
The command prompt will ask for your username, password and second factor authentication.


- [ ] Run the following command to start the delivery:
```bash
taca -c <config_path>/TACA/sthlm_taca_<instrument_config>_delivery.yml deliver --cluster dds project <project_id>
```

- [ ] Write a running note that the delivery has been started

```text
Started the delivery to DDS of project `DDS_project_id`. <author_signature>
```

- [ ] Check in [Charon](<charon_url>/project/<project_id>) that the _Delivery Status_ column changed from _STALE_ to *IN_PROGRESS*

- [ ] Release the delivery to the user:
```bash
taca -c <config_path>/TACA/sthlm_taca_<instrument_config>_delivery.yml deliver --cluster dds release-dds-project --dds_project <DDS_project_id> --no-dds-mail <project_id>
```

- [ ] Close the `screen` session


### Notifying the user

- [ ] Log into Zendesk
- [ ] Create a new ticket
- [ ] Add the contact person as a _Requester_
- [ ] In CC, add:
  - PI
  - Bioinfo contact (user end)
  - Anyone else from the GenStat project description
- [ ] as follower add:
  - Data flow area lead (optional)
  - Responsible project coordinator
  - (for Application projects) lab responsible
  - (for Application projects) Applications lab team leader
- [ ] Set _Project name_ field to <project_name> (format: `<username>_<year>_<index>`)
- [ ] Select _Form_ -> _Data delivery_
- [ ] Complete all the fields
- [ ] Apply the Macro _Delivery - Raw Data (with fields)_
- [ ] Add the following attachments to the email:
  - Project report
  - Info.txt files
  - MultiQC report
- [ ] Submit the ticket as _Solved_

Open the LIMS _Project summary_ page:

- On GenStat, go to the _Samples_ tab
- Click on any of the samples in the _Sample_ column (the first time to open the LIMS login page, and the second time to open the samples view)
- Click on the _Project Summary_ button

Set the following fields:

- [ ] Enter the delivery date in _All raw data delivered_
- [ ] Put your signature in the _Signature All raw data delivered_
- [ ] Click on _Record Changes | Run_

On GenStat, open the [bioinfo tab](<genstat_url>/bioinfo/<project_id>):

- [ ] Enter the delivery date in the _Data delivered_ field
- [ ] Click on _Save_
- [ ] Write a running note that the delivery has been completed

```text
All data delivered to the DDS project `DDS_project_id` and user informed by email. <author_signature>
```

---
