## Monitoring / documenting the bioinformatic QC on Genomic Status

> Note: The procedures in this document apply for data generated both by Illumina and Element sequencing machines at National Genomics Infrastructure (NGI) Stockholm, Science for Life Laboratory. Only the Illumina data flow is accredited.

Open [GenStat deliveries](<genstat_url>/deliveries) and find the project you are interested in, and click on the project id to open the project status page.

::: {.callout-note}
If you provided the project id when generating this checklist, you can access it via [this link](<genstat_url>/project/<project_id>).
:::

- [ ] Check the running notes for anything that needs to be taken into account during the QC
- [ ] Check the number of lanes/units ordered and obtained

## Aggregate reads in the LIMS _Project summary_ page
Open the LIMS _Project summary_ page:

- On GenStat, go to the *Samples* tab
- Click on any of the samples in the *Sample* column (the first time to open the LIMS login page, and the second time to open the samples view)
- Click on the *Project Summary* button

On the LIMS page:

- [ ] Click on _Reads Aggregation | Run_


### Check Yield and quality QC

For samples, check the following:

- [ ] Total reads (based on number of samples and total number of reads ordered)
- [ ] Q30 (see @tbl-q30)
- [ ] If yield and quality has been reached enter the sequencing date in _All samples sequenced_
- [ ] Put your signature in the _Signature All samples sequenced_
- [ ] Check other fields for correctness
- [ ] Click on _Reads Aggregation | Run_

In the table at the bottom of the page, the *QC* column refers to whether the sample has to be delivered or not.

- [ ] Set the value of the _QC_ column accordingly (i.e. whether the sample has to be delivered or not)
- [ ] Set the value of the _Set App QC_ column to _N/A_ (unless they are RNA-seq samples)
- [ ] Click on _Record Changes | Run_


### Data organisation on the UPPMAX cluster

- [ ] Log into Miarka

::: {.callout-tip title="Activate the production environment [OPTIONAL]"}
`source <config_path>/sourceme_sthlm.sh && source activate NGI`
:::

- [ ] Start the data organisation by running the following command:

```bash
cd <incoming_path>/<instrument_path>

ngi_pipeline_start.py organize flowcell <flowcell_id> -p <project_id>
```

::: {.callout-tip}
The `project_id` and `flowcell_id` can be found either in the GenStat running notes or at the top of the bioinfo tab
:::

Once the data organisation is complete:

- [ ] Check on [Charon](<charon_url>/project/<project_id>) that the *Status* column changed from *FRESH* to *STALE*

### Basic QC reports and contamination screen

On Miarka:

- [ ] Submit the QC jobs as follows:

```bash
ngi_pipeline_start.py qc project <ngi_path>/DATA/<project_id>
```

- [ ] Write a running note saying that the fastqc and fastq_screen jobs have been started

```text
Data organized and QC started for <project_id> samples on <flowcell_id>. <author_signature>
```

- [ ] Sign the note and add the required tags

You can check that the jobs have been submitted or are running by using the following command:

```bash
jobinfo | grep <project_id>
```

### Contamination screen / MultiQC report generation

Once the jobs are finished (i.e. the `jobinfo` command does not return any entry):

- [ ] Move to the project directory and submit the multiqc job:

```bash
cd <ngi_path>/ANALYSIS/<project_id> && multiqc qc_ngi
```

In the command line output:

- [ ] Check that the total number of reports matches the number of samples (it should be twice the number of samples)

- [ ] If opened, refresh the GenStat page, so that the MultiQC report will be listed in the *Reports* tab

Open the MultiQC report and check the following:

  - [ ] The FastQ Screen results match the expectations, based on the information about the samples
  - [ ] The duplication levels are within acceptable limits
  - [ ] Mean Quality Scores are in the green zone
  - [ ] The "Per Base N Content" does not exceed 10% in any given cycle or 5% in more than 10% of the cycles

Open the [bioinfo tab](<genstat_url>/bioinfo/<project_id>):

- [ ] Fill all the fastq_screen field according to the results of the MultiQC report

::: {.callout-tip title="Write a running note [OPTIONAL]"}
- [ ] Write a running note if there are things to bring up from the report: `MultiQC report has been generated for <project_id>. <author_signature>`
- [ ] Sign the note and add the required tags
:::

---

## Appendix

### Positive and negative controls

Positive and negative controls are valid for a calendar year, and can be found in their own P.Ositive and N.Egative projects. In general, add them only if it explicitly stated in the running notes.


### Lane yields

|   Platform   |            Type             | Yield (Millions) |
|:------------:|:---------------------------:|:----------------:|
|    MiSeq     |             v2              |        10        |
|    MiSeq     |             v3              |        18        |
|    MiSeq     |           Nano v2           |       0.75       |
|    MiSeq     |   Micro (not accredited)    |        3         |
| NextSeq 2000 |     P1 (not accredited)     |       100        |
| NextSeq 2000 |     P2 (not accredited)     |       400        |
| NextSeq 2000 | P3 2 x 300 (not accredited) |       300        |
| NextSeq 2000 |     P2 (not accredited)     |     1100 \*      |
| NovaSeqXPlus |            1.5B             |       750        |
| NovaSeqXPlus |             10B             |       1200       |
| NovaSeqXPlus |             25B             |       3000       |
| NovaSeqXPlus |          Universal          |       600        |

: Lane yields for Illumina flowcells. {#tbl-illumina-yields .striped .hover}

\* The reads are distributed over two lanes that are not physically separated but listed as separate lanes in the output file structure


### Elements yields

| Cycle Kit  | Output     | Cloudbreak Ultra Q Kits | Cloudbreak Freestyle (FS) Kits | **Cloudbreak Kits** |
|:----------:|:----------:|:-----------------------:|:------------------------------:|:-------------------:|
| 150        | Low        | -                    | 100                            | -                |
| 150        | Medium     | -                    | 500                            | 500                 |
| 150        | High       | -                    | 1000                           | 1000                |
| 300        | -       | 800                     | -                           | -                |
| 300        | Low        | -                    | 250                            | 250                 |
| 300        | Medium     | -                    | 500                            | 500                 |
| 300        | High       | -                    | 1000                           | 1000                |
| 600        | Medium     | -                    | 100                            | 100                 |
| 600        | High       | -                    | 300                            | 300                 |

: Lane yields for AVITI flowcells. {#tbl-elements-yields .striped .hover}


### Units yields

| Library Type               | Universal Units                                                     | Specific Lanes                                                                                             |
|:--------------------------:|:-------------------------------------------------------------------:|:----------------------------------------------------------------------------------------------------------:|
| **user supplied**          | **lane project yield** is 90% of the sum of the units for each lane | **Lane yield** reached the required levels                                                                 |
|                            |                                                                     |                                                                                                            |
| (passed reception control) |                                                                     |                                                                                                            |
| **in-house**               | **lane project yield** is 90% of the sum of the units for each lane | [entire lanes:]{.underline} **Lane yield** reached the required levels                                     |
|                            |                                                                     |                                                                                                            |
|                            |                                                                     | [shared lanes:]{.underline} **lane project yield** is equal or higher as the fraction of the lane ordered. |

: Overview of yield requirement for projects by lane. {#tbl-units-yields .striped .hover}


### Q30 thresholds

|                    | MiSeq | NextSeq | NovaSeq |
|:------------------:|:-----:|:-------:|:-------:|
| 2x50 bp (or below) |  80%  |   80%   |   85%   |
|      2x100 bp      |  75%  |   80%   |   80%   |
|      2x150 bp      |  70%  |   75%   |   75%   |
|      2x250 bp      |  60%  |   75%   |   75%   |

: Base-calling accuracy based on the Q score (Phread quality score) of the reads. {#tbl-q30 .striped .hover}


### Undetermined reads thresholds

| Platform |       Setup       |    WARN threshold    |
|:--------:|:-----------------:|:--------------------:|
|  MiSeq   | Single index read |         10%          |
|  MiSeq   |  Dual index read  |         20%          |
| NextSeq  |        Any        |         10%          |
| NovaSeq  |        Any        |         10%          |
| AVITI 24 |        Any        | 10% (including PhiX) |

: The thresholds are based on amount of PhiX added to the library (i.e. 1%); if more than 1% is added, the thresholds should be adjusted accordingly. {#tbl-undetermined .striped .hover}


---
